# Generated by Django 2.1 on 2020-05-11 11:04

import django.core.validators
from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('is_logged_in', restapi.models.CustomBooleanField(default=False)),
                ('auth_token', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
